version: '3.8'
services:
  springboot-app:
    image: eclipse-temurin:17-jdk-noble
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_USERNAME: HELLO
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle_db:1521/FREEPDB1
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: >
      bash -c "./mvnw clean install && java -jar target/*.jar"
    depends_on:
      oracle_db:
        condition: service_healthy
  oracle_db:
    container_name: oracle_db
    image: gvenzl/oracle-free:23-full-faststart
    ports:
      - "1521:1521"
      - "4000:4000"
    environment:
      ORACLE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      APP_USER: HELLO
      APP_USER_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    healthcheck:
      test: ["CMD", "healthcheck2.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 180s
    volumes:
      - ./sql:/container-entrypoint-initdb.d
